### ISSUE TITLE
Feature Request: Notify about old notes

### ISSUE THREAD

**Issue by sundevista** [tadashi-aikawa/obsidian-old-note-admonitor#1]
It's great I can see old note warning on the top. But it'd be cool to get notified about old notes once per specified time using built-in Obsidian notifications.

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @decatetsu :)

> get notified about old notes once per specified time using built-in Obsidian notifications.

I think it is a bit noisy. However, it might be helpful to get all notes expired in the vault.

**Comment by sundevista** [comment]
OK, then I close the issue
